# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Semáforo electoral
email: info@ciudadanointeligente.org
description: "Campañas limpias y reglas parejas para todos enriquecen las elecciones. No dejemos que se ensucie nuestra democracia; fiscalicemos entre todos las campañas electorales."
baseurl: "http://semaforoelectoral.cl/" # the subpath of your site, e.g. /blog
url: "http://semaforoelectoral.cl" # the base hostname & protocol for your site
twitter_username: ciudadanoi
github_username:  ciudadanointeligente

# Build settings
markdown: kramdown
